Name              = "prolic"
Enabled           = true
Users             = ["user1", "user2"]
Interval 	  = 10000000000
ID       	  = 1234567890
Labels       	  = [123,456]
Port              = 6060

[Postgres]
Enabled           = true
Port              = 8080
Hosts             = ["192.168.1.1", "192.168.1.2", "192.168.1.3"]
AvailabilityRatio = 12.3213
DBName            = "user"
